# Generated by Django 3.0.3 on 2020-02-19 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
